### ISSUE TITLE
TypeError: NutritionFacts is not a constructor

### ISSUE THREAD

**Issue by roboflank** [eliash91/nutrition-facts#1]
`const NF = new NutritionFacts(process.env.USDA_NDB_API_KEY);`
          ` ^`

`TypeError: NutritionFacts is not a constructor`

Am running into the above error.
Any work around?

**Comment by eliashussary** [comment]
Can you share your script?

**Comment by roboflank** [comment]
Am just using the Demo script.

**Comment by eliashussary** [comment]
Okay, it was written using es6 modules oppose to commonjs.

Ensure you are importing/requiring correctly, notice the ``` .default ``` on my require statement.

```Javascript

// es6
import NutritionFacts from 'nutrition-facts'

// commonjs
const NutritionFacts = require('nutrition-facts').default

```

**Comment by roboflank** [comment]
Thanks :)
